-- Script simplificado para crear las tablas del sistema BiblioSystem

-- Crear tabla de usuarios
CREATE TABLE usuarios (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    apellido VARCHAR2(100) NOT NULL,
    email VARCHAR2(150) UNIQUE NOT NULL,
    username VARCHAR2(50) UNIQUE NOT NULL,
    password_hash VARCHAR2(255) NOT NULL,
    tipo_usuario VARCHAR2(20) NOT NULL CHECK (tipo_usuario IN ('SUPERADMIN', 'ADMIN', 'BIBLIOTECARIO')),
    activo NUMBER(1) DEFAULT 1 CHECK (activo IN (0, 1)),
    fecha_creacion TIMESTAMP DEFAULT SYSTIMESTAMP,
    ultimo_acceso TIMESTAMP
);

-- Crear tabla de libros
CREATE TABLE libros (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    isbn VARCHAR2(20) UNIQUE NOT NULL,
    titulo VARCHAR2(255) NOT NULL,
    autor VARCHAR2(255) NOT NULL,
    editorial VARCHAR2(150),
    anio_publicacion NUMBER(4),
    categoria VARCHAR2(100),
    cantidad_total NUMBER DEFAULT 1 CHECK (cantidad_total >= 0),
    cantidad_disponible NUMBER DEFAULT 1 CHECK (cantidad_disponible >= 0),
    descripcion CLOB,
    activo NUMBER(1) DEFAULT 1 CHECK (activo IN (0, 1)),
    fecha_registro TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT chk_cantidad CHECK (cantidad_disponible <= cantidad_total)
);

-- Crear tabla de préstamos
CREATE TABLE prestamos (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    libro_id NUMBER NOT NULL,
    usuario_id NUMBER NOT NULL,
    bibliotecario_id NUMBER NOT NULL,
    fecha_prestamo TIMESTAMP DEFAULT SYSTIMESTAMP,
    fecha_devolucion_esperada DATE NOT NULL,
    fecha_devolucion_real TIMESTAMP,
    estado VARCHAR2(20) DEFAULT 'ACTIVO' CHECK (estado IN ('ACTIVO', 'DEVUELTO', 'VENCIDO')),
    observaciones VARCHAR2(500),
    multa NUMBER(10,2) DEFAULT 0,
    CONSTRAINT fk_prestamo_libro FOREIGN KEY (libro_id) REFERENCES libros(id),
    CONSTRAINT fk_prestamo_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id),
    CONSTRAINT fk_prestamo_bibliotecario FOREIGN KEY (bibliotecario_id) REFERENCES usuarios(id)
); 